/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import SkillPackage.BaseSkill;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author FREE
 */
public class CartaSkill extends javax.swing.JPanel {
    public boolean painel_informativo_ativado = false;
    JFrame father = null;
    BaseSkill skill;
    /**
     * Creates new form CartaSkill
     */
    public CartaSkill(BaseSkill skill,JFrame father) {
        initComponents();
        if (skill!=null)
        {
            this.skill = skill;
            lbNome.setText( skill.getNome() );
        }
        else
        {
            btInformacao.setEnabled(false);
            try{
                lbImagem.setIcon( new ImageIcon( ImageIO.read( new File(getClass().getResource("/View/Imagens/x_icon_200x200.png").getFile()) ) ) );
            }
            catch(Exception e)
            {
                e.printStackTrace();
                System.out.println("erro ao carregar imagem!");
            }
        }
        this.father = father;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagem = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        btInformacao = new javax.swing.JButton();

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/skilldefault_icon.jpg"))); // NOI18N

        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btInformacao.setText("?");
        btInformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInformacao, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btInformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformacaoActionPerformed
        // TODO add your handling code here:
        if (!painel_informativo_ativado)
        {
            CartaSkillDetalhada novo_frame = new CartaSkillDetalhada(skill);
            novo_frame.setVisible(true);
        }
        else
        {
            father.dispose();
        }
    }//GEN-LAST:event_btInformacaoActionPerformed

    public void setButtonText(String text)
    {
        btInformacao.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInformacao;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbNome;
    // End of variables declaration//GEN-END:variables
}
