/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Itens.ItemBase;
import java.awt.FlowLayout;
import javax.swing.SwingConstants;

/**
 *
 * @author FREE
 */
public class CartaItemDetalhada extends javax.swing.JFrame {

    /**
     * Creates new form CartaItemDetalhada
     */
    public CartaItemDetalhada(ItemBase item) {
        initComponents();
        CartaItens cartaNova = new CartaItens(item,null,false);
        cartaNova.desabilitarTodosBotoes();
        
        pCartaItens.setLayout(new FlowLayout(SwingConstants.LEADING,0,0));
        pCartaItens.add(cartaNova);
        
        taDescricao.setText(item.getDescricao());
        taDescricao.setLineWrap(true);
        taDescricao.setWrapStyleWord(true);
        
        ViewGlobal.centralizarJanela(this);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCartaItens = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pCartaItens.setBackground(new java.awt.Color(255, 0, 0));
        pCartaItens.setPreferredSize(new java.awt.Dimension(165, 369));

        javax.swing.GroupLayout pCartaItensLayout = new javax.swing.GroupLayout(pCartaItens);
        pCartaItens.setLayout(pCartaItensLayout);
        pCartaItensLayout.setHorizontalGroup(
            pCartaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        pCartaItensLayout.setVerticalGroup(
            pCartaItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        getContentPane().add(pCartaItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 0, 380, 280));

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 279, 380, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pCartaItens;
    private javax.swing.JTextArea taDescricao;
    // End of variables declaration//GEN-END:variables
}
