/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControleArena;
import Model.Criaturas.Elesis;
import Model.Criaturas.Heroi;
import Model.Criaturas.Jogador;
import Model.Habilidades.HabilidadeBase;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author FREE
 */
public class HeroiSelecionado extends javax.swing.JFrame {
    private ControleArena controle;
    /**
     * Creates new form HeroiSelecionado
     */
    public HeroiSelecionado(Jogador jogador,Heroi heroi,ControleArena controle) {
        initComponents();
        this.controle = controle;
        controle.escolha = null;
        
        JPanel carta_heroi = new CartaCriatura(heroi,false);
        pHeroiCartao.setLayout(new FlowLayout(SwingConstants.LEADING,0,0));
        pHeroiCartao.add(carta_heroi);
        
        lbNivel.setText("Nivel : " + heroi.getLevel());
        
        lbVidaMaxima.setText( Integer.toString( heroi.getMaxPontosVida().intValue() ) );
        
        int tamanho_altura = pRolagemHabilidades.getSize().height;
        pRolagemHabilidades.setBackground(Color.DARK_GRAY);
        pRolagemHabilidades.setPreferredSize(new Dimension(0,tamanho_altura));
        pRolagemHabilidades.setLayout(new FlowLayout(SwingConstants.LEADING,10,0));
        
        for (HabilidadeBase habilidade : heroi.getListaDeHabilidades())
        {
            JPanel carta_habilidade = new CartaHabilidade(habilidade);
            pRolagemHabilidades.add(carta_habilidade);
            pRolagemHabilidades.setPreferredSize(new Dimension(pRolagemHabilidades.getPreferredSize().width + 138,tamanho_altura));
        }
        pItemArma.setLayout(new FlowLayout(SwingConstants.LEADING,0,0));
        CartaItens panel_arma = new CartaItens(heroi.getArma(),controle,false);
        pItemArma.add(panel_arma);
        if (jogador.getArmas().size()==0)
        {
            panel_arma.mudarEstadoDoBotao(false);
        }
        if (heroi.getArma()!=null)
        {
            panel_arma.mudarEstadoDoBotao(true);
        }
        panel_arma.mudarTipo(0);
        
        pItemArmor.setLayout(new FlowLayout(SwingConstants.LEADING,0,0));
        CartaItens panel_armor = new CartaItens(heroi.getArmadura(),controle,false);
        pItemArmor.add(panel_armor);
        if (jogador.getArmaduras().size()==0)
        {
            panel_armor.mudarEstadoDoBotao(false);
        }
        if (heroi.getArmadura()!=null)
        {
            panel_armor.mudarEstadoDoBotao(true);
        }
        panel_arma.mudarTipo(1);
        
        JPanel panel_xp_possuida = new JPanel();
        panel_xp_possuida.setBackground(Color.GREEN);
        JPanel panel_xp_faltando = new JPanel();
        panel_xp_faltando.setBackground(Color.RED);
        int tamanho_total = pProgressoXP.getSize().width;
        int altura = pProgressoXP.getSize().height;
        int tamanho_xp_possuida;
        if (heroi.getXpAtual() >= 0.00)
        {
            tamanho_xp_possuida = new Double(heroi.getXpAtual()*(tamanho_total+0.00)/heroi.getRequerimentoXp()).intValue();
        }
        else
        {
            tamanho_xp_possuida = 0;
        }
        //System.out.println("tamanho_");
        
        panel_xp_possuida.setPreferredSize(new Dimension(tamanho_xp_possuida,altura));
        panel_xp_faltando.setPreferredSize(new Dimension(tamanho_total - tamanho_xp_possuida,altura));
        
        pProgressoXP.setLayout(new FlowLayout(SwingConstants.LEADING,0,0));
        pProgressoXP.add(panel_xp_possuida);
        pProgressoXP.add(panel_xp_faltando);
        pProgressoXP.setBackground(Color.PINK);
        pack();
        ViewGlobal.centralizarJanela(this);
        //System.out.println("panel_xp_po = " + panel_xp_possuida.getSize());
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pRolagemHabilidades = new javax.swing.JPanel();
        pHeroiCartao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pProgressoXP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbNivel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbVidaMaxima = new javax.swing.JLabel();
        pItemArma = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pItemArmor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 600));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 10, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 585));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Habilidades");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 21, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pRolagemHabilidades.setPreferredSize(new java.awt.Dimension(300, 219));

        javax.swing.GroupLayout pRolagemHabilidadesLayout = new javax.swing.GroupLayout(pRolagemHabilidades);
        pRolagemHabilidades.setLayout(pRolagemHabilidadesLayout);
        pRolagemHabilidadesLayout.setHorizontalGroup(
            pRolagemHabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pRolagemHabilidadesLayout.setVerticalGroup(
            pRolagemHabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pRolagemHabilidades);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 76, 475, 223));

        pHeroiCartao.setBackground(new java.awt.Color(153, 153, 153));
        pHeroiCartao.setPreferredSize(new java.awt.Dimension(280, 380));

        javax.swing.GroupLayout pHeroiCartaoLayout = new javax.swing.GroupLayout(pHeroiCartao);
        pHeroiCartao.setLayout(pHeroiCartaoLayout);
        pHeroiCartaoLayout.setHorizontalGroup(
            pHeroiCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        pHeroiCartaoLayout.setVerticalGroup(
            pHeroiCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(pHeroiCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Inicio Barra XP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 521, -1, -1));

        pProgressoXP.setBackground(new java.awt.Color(204, 0, 153));
        jPanel1.add(pProgressoXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 546, 1234, 29));

        jLabel3.setText("Proximo Nivel");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 521, -1, -1));

        lbNivel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNivel.setText("Nivel");
        jPanel1.add(lbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 481, 1234, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Vida :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 396, -1, -1));

        lbVidaMaxima.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbVidaMaxima.setText("jLabel5");
        jPanel1.add(lbVidaMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 396, -1, -1));

        pItemArma.setBackground(new java.awt.Color(255, 204, 51));
        pItemArma.setPreferredSize(new java.awt.Dimension(165, 369));

        javax.swing.GroupLayout pItemArmaLayout = new javax.swing.GroupLayout(pItemArma);
        pItemArma.setLayout(pItemArmaLayout);
        pItemArmaLayout.setHorizontalGroup(
            pItemArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        pItemArmaLayout.setVerticalGroup(
            pItemArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jPanel1.add(pItemArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 76, 163, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Armadura");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 21, -1, -1));

        pItemArmor.setBackground(new java.awt.Color(204, 204, 0));
        pItemArmor.setPreferredSize(new java.awt.Dimension(165, 369));

        javax.swing.GroupLayout pItemArmorLayout = new javax.swing.GroupLayout(pItemArmor);
        pItemArmor.setLayout(pItemArmorLayout);
        pItemArmorLayout.setHorizontalGroup(
            pItemArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        pItemArmorLayout.setVerticalGroup(
            pItemArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jPanel1.add(pItemArmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 76, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Arma");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 21, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 20, 460));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1240, 20));

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 510, 30));

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 352, 464, 100));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        controle.frame_a_exibir = FrameExibido.TELA_INICIAL;
        controle.criarProximoFrame();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeroiSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeroiSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeroiSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeroiSelecionado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jogador jogador = new Jogador();

                Heroi mc = new Elesis(null);

                jogador.getLista_de_herois().add(mc);
                
                System.out.println(mc.getRequerimentoXp());
                
                mc.addXP(90.0);
                
                new HeroiSelecionado(null,mc,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbVidaMaxima;
    private javax.swing.JPanel pHeroiCartao;
    private javax.swing.JPanel pItemArma;
    private javax.swing.JPanel pItemArmor;
    private javax.swing.JPanel pProgressoXP;
    private javax.swing.JPanel pRolagemHabilidades;
    // End of variables declaration//GEN-END:variables
}
